### ISSUE TITLE
本地安装mongo和redis后点击登录提示‘用户不存在’，前端对这个不是太熟悉，这个需要怎么操作

### ISSUE THREAD

**Issue by PirateQiang** [ZhengLinPing/vue-permission-admin#1]

**Comment by PirateQiang** [comment]
大神求指导

**Comment by dnsritch** [comment]
估计是数据库里没有相应的数据吧

**Comment by ZhengLinPing** [comment]
先把根目录dbs下的数据导入数据库：
在mongodb的bin目录下执行
mongorestore  admin -h 127.0.0.1:27077 -db koa dbpath

**Comment by ZhengLinPing** [comment]
先把项目根目录的dbs中的数据导入数据库
在mongodb安装目录的bin目录执行
`mongorestore -d koa <path>`
